
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri May 31 10:51:53 CST 2024
//----------------------------------------------------

package ajedrez;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENROQUE_LARGO = 12;
  public static final int COLUMNA = 2;
  public static final int COMMENT_LIG_VENTAJA_BLANCA = 23;
  public static final int FILA = 3;
  public static final int PEON = 4;
  public static final int N = 31;
  public static final int COMMENT_LIG_VENTAJA_NEGRA = 24;
  public static final int CAPTURA = 13;
  public static final int ALFIL = 8;
  public static final int TORRE = 7;
  public static final int COMMENT_INCERTIDUMBRE = 29;
  public static final int COMMENT_DUDOSA = 21;
  public static final int JAQUE_MATE = 15;
  public static final int COMMENT_COMPENSADO = 30;
  public static final int PROMOCION = 10;
  public static final int EOF = 0;
  public static final int CABALLO = 9;
  public static final int JAQUE = 14;
  public static final int COMMENT_VENTAJA_BLANCA = 25;
  public static final int COMMENT_MUY_BUENA = 18;
  public static final int COMMENT_BUENA = 16;
  public static final int error = 1;
  public static final int COMMENT_VENTAJA_DECISIVA_BLANCA = 27;
  public static final int COMMENT_INTERESANTE = 20;
  public static final int COMMENT_MALA = 17;
  public static final int COMMENT_VENTAJA_DECISIVA_NEGRA = 28;
  public static final int COMMENT_MUY_MALA = 19;
  public static final int DAMA = 5;
  public static final int COMMENT_VENTAJA_NEGRA = 26;
  public static final int REY = 6;
  public static final int ENROQUE_CORTO = 11;
  public static final int COMMENT_IGUALDAD = 22;
}

